title: Federico Dami치n Schonborn
baseURL: https://federicoschonborn.me/

enableGitInfo: yes
markup:
  goldmark:
    renderer:
      unsafe: yes

disableKinds:
  - taxonomy
  - term

languages:
  en:
    languageName: English
    weight: 0
    contentDir: content/en
    params:
      description: Personal site for Federico Dami치n Schonborn
  es:
    languageName: Espa침ol
    weight: 1
    contentDir: content/es
    params:
      description: Sitio personal de Federico Dami치n Schonborn

params:
  source: https://github.com/FedericoSchonborn/federicoschonborn.github.io
